-- =============================================================================
-- FILE: 02_LOOKUP_CODE_VALUES_TBL.sql
-- DESC: MMUCC v5 Lookup Code Values table.
--       Stores all coded values for every lookup type defined in
--       LOOKUP_CODE_TYPES_TBL. Replaces 7 separate MySQL reference tables.
-- DB:   Oracle 19c
-- =============================================================================

CREATE TABLE LOOKUP_CODE_VALUES_TBL (
    LCV_ID                          NUMBER          GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_LCV PRIMARY KEY,
    LCV_TYPE_CODE                   VARCHAR2(30)    NOT NULL,
    LCV_VALUE_CODE                  VARCHAR2(10)    NOT NULL,
    LCV_FIELD_1                     VARCHAR2(500),
    LCV_FIELD_2                     VARCHAR2(200),
    LCV_FIELD_3                     VARCHAR2(200),
    LCV_FIELD_4                     VARCHAR2(200),
    LCV_FIELD_5                     VARCHAR2(200),
    LCV_CREATED_BY                  VARCHAR2(100)   NOT NULL,
    LCV_CREATED_DT                  DATE            DEFAULT SYSDATE NOT NULL,
    LCV_MODIFIED_BY                 VARCHAR2(100),
    LCV_MODIFIED_DT                 DATE,
    LCV_LAST_UPDATED_ACTIVITY_CODE  VARCHAR2(20)    NOT NULL,
    CONSTRAINT UQ_LCV_TYPE_VALUE UNIQUE (LCV_TYPE_CODE, LCV_VALUE_CODE)
);

-- ---------------------------------------------------------------------------
-- Table comment
-- ---------------------------------------------------------------------------
COMMENT ON TABLE LOOKUP_CODE_VALUES_TBL IS
    'Stores all coded lookup values for every domain defined in LOOKUP_CODE_TYPES_TBL. The meaning of FIELD_1 through FIELD_5 varies by LCV_TYPE_CODE and is documented in the corresponding LCT_FIELD_N_DESC columns of LOOKUP_CODE_TYPES_TBL.';

-- ---------------------------------------------------------------------------
-- Column comments
-- ---------------------------------------------------------------------------
COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_ID IS
    'Surrogate primary key, system-generated identity column.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_TYPE_CODE IS
    'Foreign key to LOOKUP_CODE_TYPES_TBL.LCT_TYPE_CODE. Identifies which lookup domain this value belongs to (e.g., CRASH_TYPE, HARMFUL_EVENT).';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_VALUE_CODE IS
    'The coded value within the lookup type. Stores MMUCC numeric codes as strings to allow leading zeros and special values (e.g., 01, 98, 99). Unique within LCV_TYPE_CODE.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_FIELD_1 IS
    'Primary descriptive field. For most types this is the human-readable description of the code. See LCT_FIELD_1_DESC in LOOKUP_CODE_TYPES_TBL for the exact meaning per type.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_FIELD_2 IS
    'Secondary attribute field. Usage varies by type (e.g., event category for HARMFUL_EVENT, KABCO letter for INJURY_STATUS). See LCT_FIELD_2_DESC.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_FIELD_3 IS
    'Tertiary attribute field. Usage varies by type. See LCT_FIELD_3_DESC.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_FIELD_4 IS
    'Quaternary attribute field. Usage varies by type. See LCT_FIELD_4_DESC.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_FIELD_5 IS
    'Quinary attribute field. Usage varies by type. See LCT_FIELD_5_DESC.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_CREATED_BY IS
    'Username or process that created this row.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_CREATED_DT IS
    'Date and time this row was created. Defaults to SYSDATE.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_MODIFIED_BY IS
    'Username or process that last modified this row. NULL if never modified.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_MODIFIED_DT IS
    'Date and time this row was last modified. NULL if never modified.';

COMMENT ON COLUMN LOOKUP_CODE_VALUES_TBL.LCV_LAST_UPDATED_ACTIVITY_CODE IS
    'Code identifying the activity (e.g., IMPORT, USER_EDIT) that last updated this row.';

-- ---------------------------------------------------------------------------
-- Index
-- ---------------------------------------------------------------------------
CREATE INDEX IDX_LCV_TYPE_CODE ON LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE);

-- ---------------------------------------------------------------------------
-- Foreign key
-- ---------------------------------------------------------------------------
ALTER TABLE LOOKUP_CODE_VALUES_TBL
    ADD CONSTRAINT FK_LCV_TYPE
    FOREIGN KEY (LCV_TYPE_CODE)
    REFERENCES LOOKUP_CODE_TYPES_TBL (LCT_TYPE_CODE);

-- ===========================================================================
-- SEED DATA
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- CRASH_TYPE (7 rows) — MMUCC C2 SF1
-- ---------------------------------------------------------------------------
INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('CRASH_TYPE', '1', 'Single Vehicle', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('CRASH_TYPE', '2', 'Two Vehicle - Same Direction', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('CRASH_TYPE', '3', 'Two Vehicle - Opposite Direction', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('CRASH_TYPE', '4', 'Two Vehicle - Intersecting Direction', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('CRASH_TYPE', '5', 'Two Vehicle - Other', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('CRASH_TYPE', '6', 'Three or More Vehicle', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('CRASH_TYPE', '99', 'Unknown', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

-- ---------------------------------------------------------------------------
-- HARMFUL_EVENT (51 rows) — MMUCC C7/V20/V21
-- FIELD_1 = Event Description, FIELD_2 = Event Category
-- ---------------------------------------------------------------------------
INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '1', 'Cross Centerline', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '2', 'Cross Median', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '3', 'End Departure', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '4', 'Downhill Runaway', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '5', 'Equipment Failure', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '6', 'Ran Off Roadway Left', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '7', 'Ran Off Roadway Right', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '8', 'Reentering Roadway', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '9', 'Separation of Units', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '10', 'Other Non-Harmful Event', 'NON_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '11', 'Cargo/Equipment Loss or Shift', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '12', 'Fell/Jumped From Motor Vehicle', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '13', 'Fire/Explosion', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '14', 'Immersion, Full or Partial', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '15', 'Jackknife', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '16', 'Other Non-Collision Harmful Event', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '17', 'Overturn/Rollover', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '18', 'Thrown or Falling Object', 'NON_COLLISION_HARMFUL', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '19', 'Animal (live)', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '20', 'Motor Vehicle in Transport', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '21', 'Other Non-Fixed Object', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '22', 'Other Non-Motorist', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '23', 'Parked Motor Vehicle', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '24', 'Pedalcycle', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '25', 'Pedestrian', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '26', 'Railway Vehicle (train, engine)', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '27', 'Strikes Object at Rest from MV in Transport', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '28', 'Struck by Falling/Shifting Cargo from MV', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '29', 'Work Zone/Maintenance Equipment', 'COLLISION_PERSON_MV', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '30', 'Bridge Overhead Structure', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '31', 'Bridge Pier or Support', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '32', 'Bridge Rail', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '33', 'Cable Barrier', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '34', 'Concrete Traffic Barrier', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '35', 'Culvert', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '36', 'Curb', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '37', 'Ditch', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '38', 'Embankment', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '39', 'Fence', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '40', 'Guardrail End Terminal', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '41', 'Guardrail Face', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '42', 'Impact Attenuator/Crash Cushion', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '43', 'Mailbox', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '44', 'Other Fixed Object (wall, building, tunnel)', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '45', 'Other Post, Pole, or Support', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '46', 'Other Traffic Barrier', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '47', 'Traffic Sign Support', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '48', 'Traffic Signal Support', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '49', 'Tree (standing)', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '50', 'Utility Pole/Light Support', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('HARMFUL_EVENT', '51', 'Unknown Fixed Object', 'COLLISION_FIXED', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

-- ---------------------------------------------------------------------------
-- WEATHER_CONDITION (12 rows) — MMUCC C11
-- ---------------------------------------------------------------------------
INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '1', 'Clear', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '2', 'Cloudy', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '3', 'Rain', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '4', 'Snow', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '5', 'Fog Smog Smoke', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '6', 'Sleet Hail', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '7', 'Blowing Snow', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '8', 'Blowing Sand Soil Dirt', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '9', 'Severe Crosswinds', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '10', 'Freezing Rain or Drizzle', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '98', 'Other', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('WEATHER_CONDITION', '99', 'Unknown', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

-- ---------------------------------------------------------------------------
-- SURFACE_CONDITION (9 rows) — MMUCC C13
-- ---------------------------------------------------------------------------
INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '1', 'Dry', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '2', 'Wet', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '3', 'Snow or Slush', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '4', 'Ice', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '5', 'Sand Mud Dirt Oil Gravel', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '6', 'Water (Standing or Moving)', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '7', 'Oil', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '98', 'Other', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('SURFACE_CONDITION', '99', 'Unknown', NULL, NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

-- ---------------------------------------------------------------------------
-- PERSON_TYPE (10 rows) — MMUCC P4 SF1
-- FIELD_1 = description, FIELD_2 = Y/N is non-motorist
-- ---------------------------------------------------------------------------
INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '1', 'Driver', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '2', 'Passenger', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '3', 'Occupant of MV Not in Transport', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '4', 'Bicyclist', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '5', 'Other Cyclist', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '6', 'Pedestrian', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '7', 'Other Pedestrian (wheelchair, skater, personal conveyance)', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '8', 'Occupant of Non-Motor Vehicle Transportation Device', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '9', 'Unknown Type of Non-Motorist', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('PERSON_TYPE', '99', 'Unknown', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

-- ---------------------------------------------------------------------------
-- INJURY_STATUS (5 rows) — MMUCC P5 (KABCO scale)
-- FIELD_1 = description, FIELD_2 = KABCO letter, FIELD_3 = requires fatal section Y/N
-- ---------------------------------------------------------------------------
INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('INJURY_STATUS', '1', '(K) Fatal Injury', 'K', 'Y', NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('INJURY_STATUS', '2', '(A) Suspected Serious Injury', 'A', 'N', NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('INJURY_STATUS', '3', '(B) Suspected Minor Injury', 'B', 'N', NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('INJURY_STATUS', '4', '(C) Possible Injury', 'C', 'N', NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('INJURY_STATUS', '5', '(O) No Apparent Injury', 'O', 'N', NULL, NULL, 'SYSTEM', 'IMPORT');

-- ---------------------------------------------------------------------------
-- BODY_TYPE (29 rows) — MMUCC V8 SF1
-- FIELD_1 = description, FIELD_2 = Y/N requires large vehicle section
-- ---------------------------------------------------------------------------
INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '1', 'All-Terrain Vehicle/ATC', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '2', 'Golf Cart', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '3', 'Snowmobile', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '4', 'Low Speed Vehicle', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '5', 'Moped or Motorized Bicycle', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '6', 'Recreational Off-Highway Vehicle', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '7', '2-Wheeled Motorcycle', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '8', '3-Wheeled Motorcycle', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '9', 'Autocycle', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '10', 'Passenger Car', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '11', 'Passenger Van fewer than 9 seats', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '12', '(Sport) Utility Vehicle', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '13', 'Pickup', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '14', 'Cargo Van', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '15', 'Construction Equipment', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '16', 'Farm Equipment', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '17', 'Single-Unit Truck', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '18', 'Truck Tractor', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '19', 'Motor Home', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '20', '9- or 12-Passenger Van', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '21', '15-Passenger Van', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '22', 'Large Limo', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '23', 'Mini-bus', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '24', 'School Bus', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '25', 'Transit Bus', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '26', 'Motorcoach', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '27', 'Other Bus Type', 'Y', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '28', 'Other Trucks', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

INSERT INTO LOOKUP_CODE_VALUES_TBL (LCV_TYPE_CODE, LCV_VALUE_CODE, LCV_FIELD_1, LCV_FIELD_2, LCV_FIELD_3, LCV_FIELD_4, LCV_FIELD_5, LCV_CREATED_BY, LCV_LAST_UPDATED_ACTIVITY_CODE)
VALUES ('BODY_TYPE', '98', 'Other', 'N', NULL, NULL, NULL, 'SYSTEM', 'IMPORT');

COMMIT;
