-- =============================================================================
-- Migration  : V3 – Align ALL crash tables with crash-service entity types
-- Service    : crash-service
-- Target DB  : mmucc5 (pre-existing database built from database/mysql/ DDL)
-- Notes      : V1 handles fresh Testcontainers installs (all BIGINT from the
--              start). V3 patches the live mmucc5 database where every table
--              was originally created with INT UNSIGNED keys.
--              V2 is owned by auth-service in the shared DB.
--              Strategy: DROP all FK constraints → MODIFY all PK/FK columns
--              to BIGINT → ADD FK constraints back. MySQL 8 enforces type
--              compatibility during DDL even with FOREIGN_KEY_CHECKS=0, so
--              every FK referencing a column being altered must be dropped
--              first, regardless of which service owns that table.
-- =============================================================================

-- ── Step 1: Drop FK constraints — deepest children first ─────────────────────



-- ── Step 2: Modify PK and FK columns to BIGINT ────────────────────────────────

-- Root table
ALTER TABLE CRASH_TBL
    MODIFY COLUMN CRS_CRASH_ID BIGINT NOT NULL AUTO_INCREMENT;

-- Level-2 tables
ALTER TABLE VEHICLE_TBL
    MODIFY COLUMN VEH_VEHICLE_ID BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN VEH_CRASH_ID   BIGINT NOT NULL;

ALTER TABLE ROADWAY_TBL
    MODIFY COLUMN RWY_ROADWAY_ID BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN RWY_CRASH_ID   BIGINT NOT NULL;

ALTER TABLE CRASH_WEATHER_CONDITION_TBL
    MODIFY COLUMN CWC_ID       BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN CWC_CRASH_ID BIGINT NOT NULL;

ALTER TABLE CRASH_SURFACE_CONDITION_TBL
    MODIFY COLUMN CSC_ID       BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN CSC_CRASH_ID BIGINT NOT NULL;

ALTER TABLE CRASH_CONTRIBUTING_ROADWAY_TBL
    MODIFY COLUMN CCR_ID       BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN CCR_CRASH_ID BIGINT NOT NULL;

ALTER TABLE PERSON_TBL
    MODIFY COLUMN PRS_PERSON_ID  BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN PRS_CRASH_ID   BIGINT NOT NULL,
    MODIFY COLUMN PRS_VEHICLE_ID BIGINT NULL;

-- Level-3 tables
ALTER TABLE VEHICLE_TRAFFIC_CONTROL_TBL
    MODIFY COLUMN VTC_ID         BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN VTC_VEHICLE_ID BIGINT NOT NULL,
    MODIFY COLUMN VTC_CRASH_ID   BIGINT NOT NULL;

ALTER TABLE VEHICLE_DAMAGE_AREA_TBL
    MODIFY COLUMN VDA_ID         BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN VDA_VEHICLE_ID BIGINT NOT NULL,
    MODIFY COLUMN VDA_CRASH_ID   BIGINT NOT NULL;

ALTER TABLE VEHICLE_SEQUENCE_EVENT_TBL
    MODIFY COLUMN VSE_ID         BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN VSE_VEHICLE_ID BIGINT NOT NULL,
    MODIFY COLUMN VSE_CRASH_ID   BIGINT NOT NULL;

ALTER TABLE PERSON_AIRBAG_TBL
    MODIFY COLUMN PAB_ID        BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN PAB_PERSON_ID BIGINT NOT NULL,
    MODIFY COLUMN PAB_CRASH_ID  BIGINT NOT NULL;

ALTER TABLE PERSON_DRIVER_ACTION_TBL
    MODIFY COLUMN PDA_ID        BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN PDA_PERSON_ID BIGINT NOT NULL,
    MODIFY COLUMN PDA_CRASH_ID  BIGINT NOT NULL;

ALTER TABLE PERSON_DL_RESTRICTION_TBL
    MODIFY COLUMN PDR_ID        BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN PDR_PERSON_ID BIGINT NOT NULL,
    MODIFY COLUMN PDR_CRASH_ID  BIGINT NOT NULL;

ALTER TABLE PERSON_DRUG_TEST_RESULT_TBL
    MODIFY COLUMN DTR_ID        BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN DTR_PERSON_ID BIGINT NOT NULL,
    MODIFY COLUMN DTR_CRASH_ID  BIGINT NOT NULL;

ALTER TABLE FATAL_SECTION_TBL
    MODIFY COLUMN FSC_ID        BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN FSC_PERSON_ID BIGINT NOT NULL,
    MODIFY COLUMN FSC_CRASH_ID  BIGINT NOT NULL;

ALTER TABLE NON_MOTORIST_TBL
    MODIFY COLUMN NMT_ID        BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN NMT_PERSON_ID BIGINT NOT NULL,
    MODIFY COLUMN NMT_CRASH_ID  BIGINT NOT NULL;

ALTER TABLE LARGE_VEHICLE_TBL
    MODIFY COLUMN LVH_ID         BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN LVH_VEHICLE_ID BIGINT NOT NULL,
    MODIFY COLUMN LVH_CRASH_ID   BIGINT NOT NULL;

ALTER TABLE VEHICLE_AUTOMATION_TBL
    MODIFY COLUMN VAT_ID         BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN VAT_VEHICLE_ID BIGINT NOT NULL,
    MODIFY COLUMN VAT_CRASH_ID   BIGINT NOT NULL;

-- Level-4 tables
ALTER TABLE NON_MOTORIST_SAFETY_EQUIPMENT_TBL
    MODIFY COLUMN NMS_ID       BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN NMS_NMT_ID   BIGINT NOT NULL,
    MODIFY COLUMN NMS_CRASH_ID BIGINT NOT NULL;

ALTER TABLE LV_SPECIAL_SIZING_TBL
    MODIFY COLUMN LVS_ID       BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN LVS_LVH_ID   BIGINT NOT NULL,
    MODIFY COLUMN LVS_CRASH_ID BIGINT NOT NULL;

ALTER TABLE VEHICLE_AUTOMATION_LEVEL_IN_VEHICLE_TBL
    MODIFY COLUMN VAI_ID       BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN VAI_VAT_ID   BIGINT NOT NULL,
    MODIFY COLUMN VAI_CRASH_ID BIGINT NOT NULL;

ALTER TABLE VEHICLE_AUTOMATION_LEVEL_ENGAGED_TBL
    MODIFY COLUMN VAE_ID       BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN VAE_VAT_ID   BIGINT NOT NULL,
    MODIFY COLUMN VAE_CRASH_ID BIGINT NOT NULL;


-- ── Step 3: Re-add FK constraints ─────────────────────────────────────────────

-- Level-2 FKs
ALTER TABLE VEHICLE_TBL
    ADD CONSTRAINT FK_VEH_CRASH FOREIGN KEY (VEH_CRASH_ID) REFERENCES CRASH_TBL (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE ROADWAY_TBL
    ADD CONSTRAINT FK_RWY_CRASH FOREIGN KEY (RWY_CRASH_ID) REFERENCES CRASH_TBL (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE CRASH_WEATHER_CONDITION_TBL
    ADD CONSTRAINT FK_CWC_CRASH FOREIGN KEY (CWC_CRASH_ID) REFERENCES CRASH_TBL (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE CRASH_SURFACE_CONDITION_TBL
    ADD CONSTRAINT FK_CSC_CRASH FOREIGN KEY (CSC_CRASH_ID) REFERENCES CRASH_TBL (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE CRASH_CONTRIBUTING_ROADWAY_TBL
    ADD CONSTRAINT FK_CCR_CRASH FOREIGN KEY (CCR_CRASH_ID) REFERENCES CRASH_TBL (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE PERSON_TBL
    ADD CONSTRAINT FK_PRS_CRASH   FOREIGN KEY (PRS_CRASH_ID)   REFERENCES CRASH_TBL   (CRS_CRASH_ID)   ON DELETE CASCADE,
    ADD CONSTRAINT FK_PRS_VEHICLE FOREIGN KEY (PRS_VEHICLE_ID) REFERENCES VEHICLE_TBL (VEH_VEHICLE_ID) ON DELETE SET NULL;

-- Level-3 FKs
ALTER TABLE VEHICLE_TRAFFIC_CONTROL_TBL
    ADD CONSTRAINT FK_VTC_VEHICLE FOREIGN KEY (VTC_VEHICLE_ID) REFERENCES VEHICLE_TBL (VEH_VEHICLE_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_VTC_CRASH   FOREIGN KEY (VTC_CRASH_ID)   REFERENCES CRASH_TBL   (CRS_CRASH_ID)   ON DELETE CASCADE;

ALTER TABLE VEHICLE_DAMAGE_AREA_TBL
    ADD CONSTRAINT FK_VDA_VEHICLE FOREIGN KEY (VDA_VEHICLE_ID) REFERENCES VEHICLE_TBL (VEH_VEHICLE_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_VDA_CRASH   FOREIGN KEY (VDA_CRASH_ID)   REFERENCES CRASH_TBL   (CRS_CRASH_ID)   ON DELETE CASCADE;

ALTER TABLE VEHICLE_SEQUENCE_EVENT_TBL
    ADD CONSTRAINT FK_VSE_VEHICLE FOREIGN KEY (VSE_VEHICLE_ID) REFERENCES VEHICLE_TBL (VEH_VEHICLE_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_VSE_CRASH   FOREIGN KEY (VSE_CRASH_ID)   REFERENCES CRASH_TBL   (CRS_CRASH_ID)   ON DELETE CASCADE;

ALTER TABLE PERSON_AIRBAG_TBL
    ADD CONSTRAINT FK_PAB_PERSON FOREIGN KEY (PAB_PERSON_ID) REFERENCES PERSON_TBL (PRS_PERSON_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_PAB_CRASH  FOREIGN KEY (PAB_CRASH_ID)  REFERENCES CRASH_TBL  (CRS_CRASH_ID)  ON DELETE CASCADE;

ALTER TABLE PERSON_DRIVER_ACTION_TBL
    ADD CONSTRAINT FK_PDA_PERSON FOREIGN KEY (PDA_PERSON_ID) REFERENCES PERSON_TBL (PRS_PERSON_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_PDA_CRASH  FOREIGN KEY (PDA_CRASH_ID)  REFERENCES CRASH_TBL  (CRS_CRASH_ID)  ON DELETE CASCADE;

ALTER TABLE PERSON_DL_RESTRICTION_TBL
    ADD CONSTRAINT FK_PDR_PERSON FOREIGN KEY (PDR_PERSON_ID) REFERENCES PERSON_TBL (PRS_PERSON_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_PDR_CRASH  FOREIGN KEY (PDR_CRASH_ID)  REFERENCES CRASH_TBL  (CRS_CRASH_ID)  ON DELETE CASCADE;

ALTER TABLE PERSON_DRUG_TEST_RESULT_TBL
    ADD CONSTRAINT FK_DTR_PERSON FOREIGN KEY (DTR_PERSON_ID) REFERENCES PERSON_TBL (PRS_PERSON_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_DTR_CRASH  FOREIGN KEY (DTR_CRASH_ID)  REFERENCES CRASH_TBL  (CRS_CRASH_ID)  ON DELETE CASCADE;

ALTER TABLE FATAL_SECTION_TBL
    ADD CONSTRAINT FK_FSC_PERSON FOREIGN KEY (FSC_PERSON_ID) REFERENCES PERSON_TBL (PRS_PERSON_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_FSC_CRASH  FOREIGN KEY (FSC_CRASH_ID)  REFERENCES CRASH_TBL  (CRS_CRASH_ID)  ON DELETE CASCADE;

ALTER TABLE NON_MOTORIST_TBL
    ADD CONSTRAINT FK_NMT_PERSON FOREIGN KEY (NMT_PERSON_ID) REFERENCES PERSON_TBL (PRS_PERSON_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_NMT_CRASH  FOREIGN KEY (NMT_CRASH_ID)  REFERENCES CRASH_TBL  (CRS_CRASH_ID)  ON DELETE CASCADE;

ALTER TABLE LARGE_VEHICLE_TBL
    ADD CONSTRAINT FK_LVH_VEHICLE FOREIGN KEY (LVH_VEHICLE_ID) REFERENCES VEHICLE_TBL (VEH_VEHICLE_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_LVH_CRASH   FOREIGN KEY (LVH_CRASH_ID)   REFERENCES CRASH_TBL   (CRS_CRASH_ID)   ON DELETE CASCADE;

ALTER TABLE VEHICLE_AUTOMATION_TBL
    ADD CONSTRAINT FK_VAT_VEHICLE FOREIGN KEY (VAT_VEHICLE_ID) REFERENCES VEHICLE_TBL (VEH_VEHICLE_ID) ON DELETE CASCADE,
    ADD CONSTRAINT FK_VAT_CRASH   FOREIGN KEY (VAT_CRASH_ID)   REFERENCES CRASH_TBL   (CRS_CRASH_ID)   ON DELETE CASCADE;

-- Level-4 FKs
ALTER TABLE NON_MOTORIST_SAFETY_EQUIPMENT_TBL
    ADD CONSTRAINT FK_NMS_NMT   FOREIGN KEY (NMS_NMT_ID)   REFERENCES NON_MOTORIST_TBL (NMT_ID)       ON DELETE CASCADE,
    ADD CONSTRAINT FK_NMS_CRASH FOREIGN KEY (NMS_CRASH_ID) REFERENCES CRASH_TBL        (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE LV_SPECIAL_SIZING_TBL
    ADD CONSTRAINT FK_LVS_LVH   FOREIGN KEY (LVS_LVH_ID)   REFERENCES LARGE_VEHICLE_TBL (LVH_ID)       ON DELETE CASCADE,
    ADD CONSTRAINT FK_LVS_CRASH FOREIGN KEY (LVS_CRASH_ID) REFERENCES CRASH_TBL         (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE VEHICLE_AUTOMATION_LEVEL_IN_VEHICLE_TBL
    ADD CONSTRAINT FK_VAI_VAT   FOREIGN KEY (VAI_VAT_ID)   REFERENCES VEHICLE_AUTOMATION_TBL (VAT_ID)       ON DELETE CASCADE,
    ADD CONSTRAINT FK_VAI_CRASH FOREIGN KEY (VAI_CRASH_ID) REFERENCES CRASH_TBL             (CRS_CRASH_ID) ON DELETE CASCADE;

ALTER TABLE VEHICLE_AUTOMATION_LEVEL_ENGAGED_TBL
    ADD CONSTRAINT FK_VAE_VAT   FOREIGN KEY (VAE_VAT_ID)   REFERENCES VEHICLE_AUTOMATION_TBL (VAT_ID)       ON DELETE CASCADE,
    ADD CONSTRAINT FK_VAE_CRASH FOREIGN KEY (VAE_CRASH_ID) REFERENCES CRASH_TBL             (CRS_CRASH_ID) ON DELETE CASCADE;
