-- =============================================================================
-- Migration  : V4 – Convert TINYINT/SMALLINT UNSIGNED data columns to INT
-- Service    : crash-service
-- Target DB  : mmucc5 (pre-existing database built from database/mysql/ DDL)
-- Notes      : The original MMUCC DDL used TINYINT UNSIGNED for coded-value
--              columns and SMALLINT UNSIGNED for count columns.  Hibernate
--              entities map all Integer fields to INT (Types#INTEGER).
--              V3 fixed PK/FK columns to BIGINT; V4 fixes the remaining data
--              columns.  Applying MODIFY COLUMN to an already-INT column in
--              Testcontainers is a no-op, so this migration is safe in both
--              environments.
-- =============================================================================

-- ── CRASH_TBL ─────────────────────────────────────────────────────────────────
ALTER TABLE CRASH_TBL
    MODIFY COLUMN CRS_CRASH_TYPE_CODE            INT NULL,
    MODIFY COLUMN CRS_FIRST_HARMFUL_EVENT_CODE   INT NULL,
    MODIFY COLUMN CRS_ROUTE_TYPE_CODE            INT NULL,
    MODIFY COLUMN CRS_ROUTE_DIRECTION_CODE       INT NULL,
    MODIFY COLUMN CRS_REF_POINT_DIRECTION_CODE   INT NULL,
    MODIFY COLUMN CRS_LOC_FIRST_HARMFUL_EVENT    INT NULL,
    MODIFY COLUMN CRS_MANNER_COLLISION_CODE      INT NULL,
    MODIFY COLUMN CRS_SOURCE_OF_INFO_CODE        INT NULL,
    MODIFY COLUMN CRS_LIGHT_CONDITION_CODE       INT NULL,
    MODIFY COLUMN CRS_JUNCTION_INTERCHANGE_FLG   INT NULL,
    MODIFY COLUMN CRS_JUNCTION_LOCATION_CODE     INT NULL,
    MODIFY COLUMN CRS_INTERSECTION_APPROACHES    INT NULL,
    MODIFY COLUMN CRS_INTERSECTION_GEOMETRY_CODE INT NULL,
    MODIFY COLUMN CRS_INTERSECTION_TRAFFIC_CTL   INT NULL,
    MODIFY COLUMN CRS_SCHOOL_BUS_RELATED_CODE    INT NULL,
    MODIFY COLUMN CRS_WORK_ZONE_RELATED_CODE     INT NULL,
    MODIFY COLUMN CRS_WORK_ZONE_LOCATION_CODE    INT NULL,
    MODIFY COLUMN CRS_WORK_ZONE_TYPE_CODE        INT NULL,
    MODIFY COLUMN CRS_WORK_ZONE_WORKERS_CODE     INT NULL,
    MODIFY COLUMN CRS_WORK_ZONE_LAW_ENF_CODE     INT NULL,
    MODIFY COLUMN CRS_CRASH_SEVERITY_CODE        INT NULL,
    MODIFY COLUMN CRS_NUM_MOTOR_VEHICLES         INT NULL,
    MODIFY COLUMN CRS_NUM_MOTORISTS              INT NULL,
    MODIFY COLUMN CRS_NUM_NON_MOTORISTS          INT NULL,
    MODIFY COLUMN CRS_NUM_NON_FATALLY_INJURED    INT NULL,
    MODIFY COLUMN CRS_NUM_FATALITIES             INT NULL,
    MODIFY COLUMN CRS_ALCOHOL_INVOLVEMENT_CODE   INT NULL,
    MODIFY COLUMN CRS_DRUG_INVOLVEMENT_CODE      INT NULL,
    MODIFY COLUMN CRS_DAY_OF_WEEK_CODE           INT NULL;

-- ── VEHICLE_TBL ───────────────────────────────────────────────────────────────
ALTER TABLE VEHICLE_TBL
    MODIFY COLUMN VEH_UNIT_TYPE_CODE             INT NULL,
    MODIFY COLUMN VEH_UNIT_NUMBER                INT NULL,
    MODIFY COLUMN VEH_BODY_TYPE_CODE             INT NULL,
    MODIFY COLUMN VEH_TRAILING_UNITS_COUNT       INT NULL,
    MODIFY COLUMN VEH_VEHICLE_SIZE_CODE          INT NULL,
    MODIFY COLUMN VEH_HM_PLACARD_FLG             INT NULL,
    MODIFY COLUMN VEH_TOTAL_OCCUPANTS            INT NULL,
    MODIFY COLUMN VEH_SPECIAL_FUNCTION_CODE      INT NULL,
    MODIFY COLUMN VEH_EMERGENCY_USE_CODE         INT NULL,
    MODIFY COLUMN VEH_SPEED_LIMIT_MPH            INT NULL,
    MODIFY COLUMN VEH_DIRECTION_OF_TRAVEL_CODE   INT NULL,
    MODIFY COLUMN VEH_TRAFFICWAY_TRAVEL_DIR_CODE INT NULL,
    MODIFY COLUMN VEH_TRAFFICWAY_DIVIDED_CODE    INT NULL,
    MODIFY COLUMN VEH_TRAFFICWAY_BARRIER_CODE    INT NULL,
    MODIFY COLUMN VEH_TRAFFICWAY_HOV_HOT_CODE    INT NULL,
    MODIFY COLUMN VEH_TRAFFICWAY_HOV_CRASH_FLG   INT NULL,
    MODIFY COLUMN VEH_TOTAL_THROUGH_LANES        INT NULL,
    MODIFY COLUMN VEH_TOTAL_AUXILIARY_LANES      INT NULL,
    MODIFY COLUMN VEH_ROADWAY_ALIGNMENT_CODE     INT NULL,
    MODIFY COLUMN VEH_ROADWAY_GRADE_CODE         INT NULL,
    MODIFY COLUMN VEH_MANEUVER_CODE              INT NULL,
    MODIFY COLUMN VEH_DAMAGE_INITIAL_CONTACT     INT NULL,
    MODIFY COLUMN VEH_DAMAGE_EXTENT_CODE         INT NULL,
    MODIFY COLUMN VEH_MOST_HARMFUL_EVENT_CODE    INT NULL,
    MODIFY COLUMN VEH_HIT_AND_RUN_CODE           INT NULL,
    MODIFY COLUMN VEH_TOWED_CODE                 INT NULL,
    MODIFY COLUMN VEH_CONTRIBUTING_CIRC_CODE     INT NULL;

-- ── ROADWAY_TBL ───────────────────────────────────────────────────────────────
ALTER TABLE ROADWAY_TBL
    MODIFY COLUMN RWY_NATIONAL_HWY_SYS_CODE    INT NULL,
    MODIFY COLUMN RWY_FUNCTIONAL_CLASS_CODE    INT NULL,
    MODIFY COLUMN RWY_ACCESS_CONTROL_CODE      INT NULL,
    MODIFY COLUMN RWY_ROADWAY_LIGHTING_CODE    INT NULL,
    MODIFY COLUMN RWY_PAVEMENT_EDGELINE_CODE   INT NULL,
    MODIFY COLUMN RWY_PAVEMENT_CENTERLINE_CODE INT NULL,
    MODIFY COLUMN RWY_PAVEMENT_LANE_LINE_CODE  INT NULL,
    MODIFY COLUMN RWY_BICYCLE_FACILITY_CODE    INT NULL,
    MODIFY COLUMN RWY_BICYCLE_SIGNED_ROUTE_CODE INT NULL,
    MODIFY COLUMN RWY_MAINLINE_LANES_COUNT     INT NULL,
    MODIFY COLUMN RWY_CROSS_STREET_LANES_COUNT INT NULL;

-- ── CRASH_WEATHER_CONDITION_TBL ───────────────────────────────────────────────
ALTER TABLE CRASH_WEATHER_CONDITION_TBL
    MODIFY COLUMN CWC_SEQUENCE_NUM INT NOT NULL,
    MODIFY COLUMN CWC_WEATHER_CODE INT NOT NULL;

-- ── CRASH_SURFACE_CONDITION_TBL ───────────────────────────────────────────────
ALTER TABLE CRASH_SURFACE_CONDITION_TBL
    MODIFY COLUMN CSC_SEQUENCE_NUM INT NOT NULL,
    MODIFY COLUMN CSC_SURFACE_CODE INT NOT NULL;

-- ── CRASH_CONTRIBUTING_ROADWAY_TBL ────────────────────────────────────────────
ALTER TABLE CRASH_CONTRIBUTING_ROADWAY_TBL
    MODIFY COLUMN CCR_SEQUENCE_NUM      INT NOT NULL,
    MODIFY COLUMN CCR_CIRCUMSTANCE_CODE INT NOT NULL;

-- ── VEHICLE_TRAFFIC_CONTROL_TBL ───────────────────────────────────────────────
ALTER TABLE VEHICLE_TRAFFIC_CONTROL_TBL
    MODIFY COLUMN VTC_SEQUENCE_NUM        INT NOT NULL,
    MODIFY COLUMN VTC_TCD_TYPE_CODE       INT NOT NULL,
    MODIFY COLUMN VTC_TCD_INOPERATIVE_CODE INT NULL;

-- ── VEHICLE_DAMAGE_AREA_TBL ───────────────────────────────────────────────────
ALTER TABLE VEHICLE_DAMAGE_AREA_TBL
    MODIFY COLUMN VDA_SEQUENCE_NUM INT NOT NULL,
    MODIFY COLUMN VDA_AREA_CODE    INT NOT NULL;

-- ── VEHICLE_SEQUENCE_EVENT_TBL ────────────────────────────────────────────────
ALTER TABLE VEHICLE_SEQUENCE_EVENT_TBL
    MODIFY COLUMN VSE_SEQUENCE_NUM INT NOT NULL,
    MODIFY COLUMN VSE_EVENT_CODE   INT NOT NULL;
