-- =============================================================================
-- V7__fix_person_column_types.sql
-- Converts all TINYINT UNSIGNED, SMALLINT UNSIGNED, and YEAR data columns in
-- the Sprint 3 tables to INT so they match Hibernate's Integer mapping.
--
-- On the live mmucc5 DB these columns were created as TINYINT/SMALLINT UNSIGNED
-- by the original DDL scripts. V6 already created them as INT on fresh
-- Testcontainers instances, so MODIFY COLUMN INT → INT is a safe no-op there.
--
-- No FK constraints are affected here — all modified columns are payload
-- (data) columns, not PK/FK identity columns (those were fixed in V3).
-- =============================================================================

-- ── PERSON_TBL ────────────────────────────────────────────────────────────────
ALTER TABLE PERSON_TBL
    MODIFY COLUMN PRS_DOB_YEAR                INT  NULL,
    MODIFY COLUMN PRS_DOB_MONTH               INT  NULL,
    MODIFY COLUMN PRS_DOB_DAY                 INT  NULL,
    MODIFY COLUMN PRS_AGE_YEARS               INT  NULL,
    MODIFY COLUMN PRS_SEX_CODE                INT  NULL,
    MODIFY COLUMN PRS_PERSON_TYPE_CODE        INT  NULL,
    MODIFY COLUMN PRS_INCIDENT_RESPONDER_CODE INT  NULL,
    MODIFY COLUMN PRS_INJURY_STATUS_CODE      INT  NULL,
    MODIFY COLUMN PRS_VEHICLE_UNIT_NUMBER     INT  NULL,
    MODIFY COLUMN PRS_SEATING_ROW_CODE        INT  NULL,
    MODIFY COLUMN PRS_SEATING_SEAT_CODE       INT  NULL,
    MODIFY COLUMN PRS_RESTRAINT_CODE          INT  NULL,
    MODIFY COLUMN PRS_RESTRAINT_IMPROPER_FLG  INT  NULL,
    MODIFY COLUMN PRS_EJECTION_CODE           INT  NULL,
    MODIFY COLUMN PRS_DL_JURISDICTION_TYPE    INT  NULL,
    MODIFY COLUMN PRS_DL_CLASS_CODE           INT  NULL,
    MODIFY COLUMN PRS_DL_IS_CDL_FLG           INT  NULL,
    MODIFY COLUMN PRS_DL_ENDORSEMENT_CODE     INT  NULL,
    MODIFY COLUMN PRS_SPEEDING_CODE           INT  NULL,
    MODIFY COLUMN PRS_DL_ALCOHOL_INTERLOCK_FLG INT NULL,
    MODIFY COLUMN PRS_DL_STATUS_TYPE_CODE     INT  NULL,
    MODIFY COLUMN PRS_DL_STATUS_CODE          INT  NULL,
    MODIFY COLUMN PRS_DISTRACTED_ACTION_CODE  INT  NULL,
    MODIFY COLUMN PRS_DISTRACTED_SOURCE_CODE  INT  NULL,
    MODIFY COLUMN PRS_CONDITION_CODE_1        INT  NULL,
    MODIFY COLUMN PRS_CONDITION_CODE_2        INT  NULL,
    MODIFY COLUMN PRS_LE_SUSPECTS_ALCOHOL     INT  NULL,
    MODIFY COLUMN PRS_ALCOHOL_TEST_STATUS_CODE INT NULL,
    MODIFY COLUMN PRS_ALCOHOL_TEST_TYPE_CODE  INT  NULL,
    MODIFY COLUMN PRS_LE_SUSPECTS_DRUG        INT  NULL,
    MODIFY COLUMN PRS_DRUG_TEST_STATUS_CODE   INT  NULL,
    MODIFY COLUMN PRS_DRUG_TEST_TYPE_CODE     INT  NULL,
    MODIFY COLUMN PRS_TRANSPORT_SOURCE_CODE   INT  NULL,
    MODIFY COLUMN PRS_INJURY_AREA_CODE        INT  NULL,
    MODIFY COLUMN PRS_INJURY_SEVERITY_CODE    INT  NULL;

-- ── PERSON_AIRBAG_TBL ─────────────────────────────────────────────────────────
ALTER TABLE PERSON_AIRBAG_TBL
    MODIFY COLUMN PAB_SEQUENCE_NUM  INT  NOT NULL,
    MODIFY COLUMN PAB_AIRBAG_CODE   INT  NOT NULL;

-- ── PERSON_DRIVER_ACTION_TBL ──────────────────────────────────────────────────
ALTER TABLE PERSON_DRIVER_ACTION_TBL
    MODIFY COLUMN PDA_SEQUENCE_NUM  INT  NOT NULL,
    MODIFY COLUMN PDA_ACTION_CODE   INT  NOT NULL;

-- ── PERSON_DL_RESTRICTION_TBL ─────────────────────────────────────────────────
ALTER TABLE PERSON_DL_RESTRICTION_TBL
    MODIFY COLUMN PDR_SEQUENCE_NUM      INT  NOT NULL,
    MODIFY COLUMN PDR_RESTRICTION_CODE  INT  NOT NULL;

-- ── PERSON_DRUG_TEST_RESULT_TBL ───────────────────────────────────────────────
ALTER TABLE PERSON_DRUG_TEST_RESULT_TBL
    MODIFY COLUMN DTR_SEQUENCE_NUM  INT  NOT NULL,
    MODIFY COLUMN DTR_RESULT_CODE   INT  NOT NULL;

-- ── FATAL_SECTION_TBL ─────────────────────────────────────────────────────────
ALTER TABLE FATAL_SECTION_TBL
    MODIFY COLUMN FSC_AVOIDANCE_MANEUVER_CODE  INT  NULL,
    MODIFY COLUMN FSC_ALCOHOL_TEST_TYPE_CODE   INT  NULL,
    MODIFY COLUMN FSC_DRUG_TEST_TYPE_CODE      INT  NULL,
    MODIFY COLUMN FSC_DRUG_TEST_RESULT         INT  NULL;

-- ── NON_MOTORIST_TBL ──────────────────────────────────────────────────────────
ALTER TABLE NON_MOTORIST_TBL
    MODIFY COLUMN NMT_STRIKING_VEHICLE_UNIT   INT  NULL,
    MODIFY COLUMN NMT_ACTION_CIRC_CODE        INT  NULL,
    MODIFY COLUMN NMT_ORIGIN_DESTINATION_CODE INT  NULL,
    MODIFY COLUMN NMT_CONTRIBUTING_ACTION_1   INT  NULL,
    MODIFY COLUMN NMT_CONTRIBUTING_ACTION_2   INT  NULL,
    MODIFY COLUMN NMT_LOCATION_AT_CRASH_CODE  INT  NULL,
    MODIFY COLUMN NMT_INITIAL_CONTACT_POINT   INT  NULL;

-- ── NON_MOTORIST_SAFETY_EQUIPMENT_TBL ────────────────────────────────────────
ALTER TABLE NON_MOTORIST_SAFETY_EQUIPMENT_TBL
    MODIFY COLUMN NMS_SEQUENCE_NUM    INT  NOT NULL,
    MODIFY COLUMN NMS_EQUIPMENT_CODE  INT  NOT NULL;

-- ── LARGE_VEHICLE_TBL ─────────────────────────────────────────────────────────
-- YEAR type columns (LVH_TRAILER*_YEAR) also converted to INT — Hibernate
-- maps Integer fields to INTEGER and cannot validate against MySQL YEAR type.
ALTER TABLE LARGE_VEHICLE_TBL
    MODIFY COLUMN LVH_CMV_LICENSE_STATUS_CODE  INT  NULL,
    MODIFY COLUMN LVH_CDL_COMPLIANCE_CODE      INT  NULL,
    MODIFY COLUMN LVH_TRAILER1_YEAR            INT  NULL,
    MODIFY COLUMN LVH_TRAILER2_YEAR            INT  NULL,
    MODIFY COLUMN LVH_TRAILER3_YEAR            INT  NULL,
    MODIFY COLUMN LVH_CARRIER_ID_TYPE_CODE     INT  NULL,
    MODIFY COLUMN LVH_CARRIER_TYPE_CODE        INT  NULL,
    MODIFY COLUMN LVH_VEHICLE_CONFIG_CODE      INT  NULL,
    MODIFY COLUMN LVH_VEHICLE_PERMITTED_CODE   INT  NULL,
    MODIFY COLUMN LVH_CARGO_BODY_TYPE_CODE     INT  NULL,
    MODIFY COLUMN LVH_HM_RELEASED_CODE         INT  NULL,
    MODIFY COLUMN LVH_AXLES_TRACTOR            INT  NULL,
    MODIFY COLUMN LVH_AXLES_TRAILER1           INT  NULL,
    MODIFY COLUMN LVH_AXLES_TRAILER2           INT  NULL,
    MODIFY COLUMN LVH_AXLES_TRAILER3           INT  NULL;

-- ── LV_SPECIAL_SIZING_TBL ────────────────────────────────────────────────────
ALTER TABLE LV_SPECIAL_SIZING_TBL
    MODIFY COLUMN LVS_SEQUENCE_NUM  INT  NOT NULL,
    MODIFY COLUMN LVS_SIZING_CODE   INT  NOT NULL;

-- ── VEHICLE_AUTOMATION_TBL ────────────────────────────────────────────────────
ALTER TABLE VEHICLE_AUTOMATION_TBL
    MODIFY COLUMN VAT_AUTOMATION_PRESENT_CODE  INT  NULL;

-- ── VEHICLE_AUTOMATION_LEVEL_IN_VEHICLE_TBL ───────────────────────────────────
ALTER TABLE VEHICLE_AUTOMATION_LEVEL_IN_VEHICLE_TBL
    MODIFY COLUMN VAI_SEQUENCE_NUM          INT  NOT NULL,
    MODIFY COLUMN VAI_AUTOMATION_LEVEL_CODE INT  NOT NULL;

-- ── VEHICLE_AUTOMATION_LEVEL_ENGAGED_TBL ──────────────────────────────────────
ALTER TABLE VEHICLE_AUTOMATION_LEVEL_ENGAGED_TBL
    MODIFY COLUMN VAE_SEQUENCE_NUM          INT  NOT NULL,
    MODIFY COLUMN VAE_AUTOMATION_LEVEL_CODE INT  NOT NULL;
